name: Build

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7', '3.7', pypy-2.7, pypy-3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install build-essential
    - name: Build
      run: |
        make install PYTHON=python
    - name: Check import
      run: |
        python tests/test_snapshot.py
    - name: Test with unittest
      run: |
        make test PYTHON=python
